export const routes = {
  home: "/",
  portfolio: "/home",
  auth: "/auth",
  login: "/auth/login",
  register: "/auth/signup",
  resetPassword: "/auth/reset-password",
  forgotPassword: "/auth/forgot-password",
  dashboard: "/dashboard",
  terms: "/terms",
  privacy: "/privacy",
  about: "/about",
  contact: "/contact",
  blog: "/blog",
};
